name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['stable', 'oldstable']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: go mod verify
      - run: go test -v -race -shuffle=on ./...
